import type { Configuration } from 'markdownlint';

/**
 * Shareable markdownlint configuration. Targets markdownlint 0.34+ rule names
 * (e.g. no-duplicate-heading instead of the legacy no-duplicate-header alias).
 */
const config: Configuration = {
  default: true,

  // Customised intent rules
  'ul-style': { style: 'dash' },
  'no-trailing-spaces': {
    br_spaces: 0,
    list_item_empty_lines: false,
  },

  // Disabled (too noisy in practice)
  'list-marker-space': false,
  'line-length': false,
  'no-inline-html': false,
  'no-duplicate-heading': false,
  'first-line-heading': false,

  // Proper-name capitalisation list (intentionally generic, no brand attribution)
  'proper-names': {
    names: [
      'JavaScript',
      'TypeScript',
      'HTML',
      'CSS',
      'AJAX',
      'JSON',
      'DOM',
      'BOM',
      'Less',
      'Sass',
      'SCSS',
      'HTTP',
      'HTTPS',
      'WebSocket',
      'ECMAScript',
      'ES2015',
      'ES2020',
      'ES2022',
      'jQuery',
      'React',
      'React Native',
      'Vue',
      'Vue.js',
      'Angular',
      'Svelte',
      'Bootstrap',
      'Tailwind CSS',
      'Vite',
      'Webpack',
      'webpack',
      'Rollup',
      'esbuild',
      'Gulp',
      'Grunt',
      'npm',
      'pnpm',
      'Yarn',
      'Babel',
      'PostCSS',
      'Vitest',
      'Jest',
      'Mocha',
      'Cypress',
      'Playwright',
      'PHP',
      'Java',
      'Go',
      'Rust',
      'Python',
      'Node.js',
      'NodeJS',
      'Deno',
      'Bun',
      'MySQL',
      'PostgreSQL',
      'MongoDB',
      'Redis',
      'SQLite',
      'Apache',
      'Nginx',
      'GitHub',
      'GitLab',
      'Bitbucket',
      'Chrome',
      'Firefox',
      'Safari',
      'Edge',
      'Opera',
      'Android',
      'iOS',
      'iPadOS',
      'macOS',
      'Windows',
      'Ubuntu',
      'Linux',
      'Debian',
      'iPhone',
      'iPad',
      'MacBook',
      'MacBook Pro',
      'MacBook Air',
      'Apple Watch',
      'Apple',
      'Google',
      'Microsoft',
      'Amazon',
      'Meta',
      'UI',
      'UX',
      'API',
      'URL',
      'URI',
      'URLs',
      'URIs',
      'OAuth',
      'JWT',
      'GraphQL',
      'REST',
      'Visual Studio Code',
    ],
    code_blocks: false,
  },
};

export default config;
